version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install Terraform
          command: |
            curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.6/terraform_1.0.6_linux_amd64.zip
            unzip terraform.zip
            sudo mv terraform /usr/local/bin/
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve